# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rubi2_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(984, 601)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-30, 0, 1013, 611))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("blue_girl.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.run_back = QtWidgets.QLabel(Form)
        self.run_back.setGeometry(QtCore.QRect(-20, -20, 211, 111))
        self.run_back.setText("")
        self.run_back.setPixmap(QtGui.QPixmap("box.jpg"))
        self.run_back.setScaledContents(True)
        self.run_back.setObjectName("run_back")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(25)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background: transparent;\n"
"color: white;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 440, 271, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("box.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 440, 261, 161))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("box.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        
        self.console_text = QtWidgets.QTextBrowser(Form)
        self.console_text.setGeometry(QtCore.QRect(200, 10, 401, 121))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(15)
        self.console_text.setFont(font)
        self.console_text.setStyleSheet("background: transparent;\n"
"border-radius: none;\ncolor: white;")
        self.console_text.setObjectName("console_text")
        
        self.date_text = QtWidgets.QTextBrowser(Form)
        self.date_text.setGeometry(QtCore.QRect(50, 500, 171, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        self.date_text.setFont(font)
        self.date_text.setStyleSheet("background: transparent;\n"
"border-radius: none;\ncolor: white;")
        self.date_text.setObjectName("date_text")
        self.time_taxt = QtWidgets.QTextBrowser(Form)
        self.time_taxt.setGeometry(QtCore.QRect(300, 500, 171, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(24)
        self.time_taxt.setFont(font)
        self.time_taxt.setStyleSheet("background: transparent;\n"
"border-radius: none;\ncolor: white;")
        self.time_taxt.setObjectName("time_taxt")
        self.speaker = QtWidgets.QLabel(Form)
        self.speaker.setGeometry(QtCore.QRect(90, 140, 421, 271))
        self.speaker.setText("")
        self.speaker.setPixmap(QtGui.QPixmap("equiler.gif"))
        self.speaker.setScaledContents(True)
        self.speaker.setObjectName("speaker")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
